name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Run Tests
        run: |
          go test -v ./...
